apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  namespace: load
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      containers:
      - name: load-generator
        image: registry.iximiuz.com/load-generator:latest
        # we use the DNS for the webserver service here to generate some background load on the cluster
        command: ["/load-generator", "http://flask-webserver.dojo", "10"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
