apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: dojo
type: Opaque
data:
  # a reminder if, like me, you run these via `echo "VALUE_HERE" | base64` instead of using the `-n` flag
  # with echo, eg - `echo -n "VALUE_HERE" | base64
  # if you don't use the `-n` flag, your base64 values will have a newline and will not work
  username: cHJvZC11c2Vy
  password: DATABASE_SECRET
