apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-data
  namespace: dojo
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
   storage: STORAGE_CAPACITY
  accessModes:
   - ReadWriteMany
  hostPath:
    path: "/tmp/k3s-data"
