apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-data-claim
  namespace: dojo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500M
