apiVersion: v1
kind: Service
metadata:
  name: logs-processor
  namespace: dojo
spec:
  selector:
    app: logs-processor
  ports:
    - protocol: TCP
      port: 80
      targetPort: TARGET_PORT
  type: ClusterIP
