apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-info
  namespace: dojo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-info
  template:
    metadata:
      labels:
        app: user-info
    spec:
      serviceAccountName: user-info-service-account
      containers:
      - name: user-info
        image: registry.iximiuz.com/user-info:latest
        resources:
          requests:
            memory: MEMORY_REQUEST
            cpu: CPU_REQUEST
          limits:
            memory: MEMORY_LIMIT
            cpu: CPU_LIMIT
        ports:
        - containerPort: 8010
        env:
          - name: ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: environment
                key: environment
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password
