apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user-info
  namespace: dojo
subjects:
- kind: ServiceAccount
  name: user-info-service-account
roleRef:
  kind: Role
  name: user-info-secret-reader
  apiGroup: rbac.authorization.k8s.io
